### ISSUE TITLE
Fatal error in "Ignore cockpit-pcp in "full" package install mode with Cockpit ≥ 326" (RHEL 9.6 and RHEL 10.0)

### ISSUE THREAD

**Issue by benblasco** [linux-system-roles/cockpit#221]
I have been running the upstream roles against RHEL boxes for a long time, but when running them against newly provisioned RHEL 9.6 and RHEL 10.0 hosts I got the following fatal error:

```
TASK [fedora.linux_system_roles.cockpit : Ignore cockpit-pcp in "full" package install mode with Cockpit ≥ 326] ***
fatal: [rhel100.nuc.blasco.id.au]: FAILED! => {"msg": "Version comparison failed: '<' not supported between instances of 'str' and 'int'"}
fatal: [rhel96.nuc.blasco.id.au]: FAILED! => {"msg": "Version comparison failed: '<' not supported between instances of 'str' and 'int'"}
```

Here are the variables I am calling the role with:
```
❯ cat group_vars/all/cockpit.yml 
cockpit_enabled: true

cockpit_started: true

cockpit_manage_firewall: true

cockpit_packages: full

cockpit_config:
  Session:
    IdleTimeout: 15

```

I believe the changes relating to this may be the culprit:
https://github.com/linux-system-roles/cockpit/pull/206

More specifically, somewhere around line 23 of tasks/setup-dnf.yml

Here are the cockpit versions running on my systems:
```
[bblasco@rhel100 ~]$ rpm -qa | grep cockpit
cockpit-bridge-334.1-1.el10_0.x86_64
cockpit-system-334.1-1.el10_0.noarch
cockpit-ws-334.1-1.el10_0.x86_64
```

```
[bblasco@rhel96 ~]$ rpm -qa | grep cockpit
cockpit-bridge-334.1-1.el9_6.x86_64
cockpit-system-334.1-1.el9_6.noarch
cockpit-ws-334.1-1.el9_6.x86_64
subscription-manager-cockpit-6-2.el9.noarch
```

Please let me know what other info you need and I will provide it ASAP.
