### ISSUE TITLE
Error with cockpit-* globbing

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/cockpit#51]
When using the latest version of linux-system-roles.cockpit from galaxy, I'm receiving the following error:
``` 
fatal: [rhel8latest]: FAILED! => {"changed": false, "failures": ["cockpit-* All matches were filtered out by exclude filtering for argument: cockpit-*"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

playbook is fairly simple, specifying the 'full' option to install all cockpit packages
```
- hosts: all
  remote_user: root

  vars:
    USE_FIREWALL: 1
  tasks:

    - name: Install RHEL/Fedora Web Console (Cockpit)
      include_role:
        name: linux-system-roles.cockpit
      vars:
        cockpit_packages: "full"   # or minimal, default

    - name: Configure Firewall for Web Console
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
      when: USE_FIREWALL|bool
```
